# Generated by Django 3.2.9 on 2021-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=20211111, max_length=100),
            preserve_default=False,
        ),
    ]
